title: Clack - Web application environment for Common Lisp
tagline: Revenge of Lisp in Web
description: >
  Clack is a web application environment for Common Lisp inspired by Python's
  WSGI and Ruby's Rack.

baseurl: ""

permalink: /news/:title

# Build settings
markdown: kramdown
