title: Clack - Web application environment for Common Lisp
tagline: Revenge of Lisp in Web
description: >
  Clack is a web application environment for Common Lisp inspired by Python's
  WSGI and Ruby's Rack.

baseurl: ""

permalink: /news/:title

# Build settings
markdown: kramdown

excerpt_separator: "<!-- sep -->"

# Links
links:
  repo: https://github.com/fukamachi/clack
  issues: https://github.com/fukamachi/clack/issues
  contrib: https://github.com/fukamachi/clack/graphs/contributors
  rss: /feed.xml
  docs: http://quickdocs.org/clack/
  api: http://quickdocs.org/clack/api

# Code samples
code:
  intro: |
    (clackup
      (lambda (env)
        '(200
          (:content-type "text/plain")
          ("Hello, Clack!"))))

  ningle: |
    (defvar *app* (make-instance 'ningle:<app>))

    (setf (ningle:route *app* "/")
          "Welcome to ningle!")

    (setf (ningle:route *app* "/login" :method :POST)
          #'(lambda (params)
              (if (authorize (getf params :|username|)
                             (getf params :|password|))
                "Authorized!"
                "Failed...Try again.")))

    (clack:clackup *app*)

  caveman: |
    (defparameter *app* (make-instance '<app>))

    @route GET "/"
    (defun index ()
      (with-layout (:title "Welcome to My site")
        (render #P"index.tmpl")))
