title: Clack - Web application environment for Common Lisp
tagline: Revenge of Lisp in Web
description: >
  Clack is a web application environment for Common Lisp inspired by Python's
  WSGI and Ruby's Rack.

baseurl: ""

permalink: /news/:title

# Build settings
markdown: kramdown

# Links
links:
  repo: https://github.com/fukamachi/clack
  issues: https://github.com/fukamachi/clack/issues
  contrib: https://github.com/fukamachi/clack/graphs/contributors
  rss: /feed.xml
  api: http://quickdocs.org/clack/api
